export type TravelPlace = {
  id: string;
  place: string;
  country: string;
  continent: string;
  lat: number;
  lng: number;
};

export const travelPlaces = [
  {
    id: "fuzhou",
    place: "Fuzhou",
    country: "China",
    continent: "Asia",
    lat: 26.0745,
    lng: 119.2965,
  },
  {
    id: "toronto",
    place: "Toronto",
    country: "Canada",
    continent: "North America",
    lat: 43.6532,
    lng: -79.3832,
  },
  {
    id: "iceland",
    place: "Reykjavik",
    country: "Iceland",
    continent: "Europe",
    lat: 64.1466,
    lng: -21.9426,
  },
  {
    id: "san-francisco",
    place: "San Francisco",
    country: "United States",
    continent: "North America",
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    id: "berlin",
    place: "Berlin",
    country: "Germany",
    continent: "Europe",
    lat: 52.52,
    lng: 13.405,
  },
  {
    id: "rome",
    place: "Rome",
    country: "Italy",
    continent: "Europe",
    lat: 41.9028,
    lng: 12.4964,
  },
  {
    id: "phuket",
    place: "Phuket",
    country: "Thailand",
    continent: "Asia",
    lat: 7.8804,
    lng: 98.3923,
  },
  {
    id: "halifax",
    place: "Halifax",
    country: "Canada",
    continent: "North America",
    lat: 44.6488,
    lng: -63.5752,
  },
  {
    id: "tokyo",
    place: "Tokyo",
    country: "Japan",
    continent: "Asia",
    lat: 35.6762,
    lng: 139.6503,
  },
  {
    id: "manila",
    place: "Manila",
    country: "Philippines",
    continent: "Asia",
    lat: 14.5995,
    lng: 120.9842,
  },
  {
    id: "sabah",
    place: "Sabah",
    country: "Malaysia",
    continent: "Asia",
    lat: 5.9804,
    lng: 116.0735,
  },
  {
    id: "kuala-lumpur",
    place: "Kuala Lumpur",
    country: "Malaysia",
    continent: "Asia",
    lat: 3.139,
    lng: 101.6869,
  },
  {
    id: "singapore",
    place: "Singapore",
    country: "Singapore",
    continent: "Asia",
    lat: 1.3521,
    lng: 103.8198,
  },
  {
    id: "taipei",
    place: "Taipei",
    country: "China",
    continent: "Asia",
    lat: 25.033,
    lng: 121.5654,
  },
  {
    id: "shanghai",
    place: "Shanghai",
    country: "China",
    continent: "Asia",
    lat: 31.2304,
    lng: 121.4737,
  },
  {
    id: "beijing",
    place: "Beijing",
    country: "China",
    continent: "Asia",
    lat: 39.9042,
    lng: 116.4074,
  },
  {
    id: "xian",
    place: "Xi'an",
    country: "China",
    continent: "Asia",
    lat: 34.3416,
    lng: 108.9398,
  },
  {
    id: "harbin",
    place: "Harbin",
    country: "China",
    continent: "Asia",
    lat: 45.8038,
    lng: 126.535,
  },
  {
    id: "chengdu",
    place: "Chengdu",
    country: "China",
    continent: "Asia",
    lat: 30.5723,
    lng: 104.0665,
  },
  {
    id: "zhejiang",
    place: "Hangzhou",
    country: "China",
    continent: "Asia",
    lat: 30.2741,
    lng: 120.1551,
  },
  {
    id: "xiamen",
    place: "Xiamen",
    country: "China",
    continent: "Asia",
    lat: 24.4798,
    lng: 118.0894,
  },
  {
    id: "shenzhen",
    place: "Shenzhen",
    country: "China",
    continent: "Asia",
    lat: 22.5431,
    lng: 114.0579,
  },
  {
    id: "changchun",
    place: "Changchun",
    country: "China",
    continent: "Asia",
    lat: 43.8171,
    lng: 125.3235,
  },
  {
    id: "montreal",
    place: "Montreal",
    country: "Canada",
    continent: "North America",
    lat: 45.5017,
    lng: -73.5673,
  },
  {
    id: "banff",
    place: "Banff",
    country: "Canada",
    continent: "North America",
    lat: 51.1784,
    lng: -115.5708,
  },
  {
    id: "los-angeles",
    place: "Los Angeles",
    country: "United States",
    continent: "North America",
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    id: "hong-kong",
    place: "Hong Kong",
    country: "China",
    continent: "Asia",
    lat: 22.3193,
    lng: 114.1694,
  },
  {
    id: "salzburg",
    place: "Salzburg",
    country: "Austria",
    continent: "Europe",
    lat: 47.8095,
    lng: 13.055,
  },
  {
    id: "cologne",
    place: "Cologne",
    country: "Germany",
    continent: "Europe",
    lat: 50.9375,
    lng: 6.9603,
  },
  {
    id: "amsterdam",
    place: "Amsterdam",
    country: "Netherlands",
    continent: "Europe",
    lat: 52.3676,
    lng: 4.9041,
  },
  {
    id: "milan",
    place: "Milan",
    country: "Italy",
    continent: "Europe",
    lat: 45.4642,
    lng: 9.19,
  },
  {
    id: "florence",
    place: "Florence",
    country: "Italy",
    continent: "Europe",
    lat: 43.7696,
    lng: 11.2558,
  },
  {
    id: "osaka",
    place: "Osaka",
    country: "Japan",
    continent: "Asia",
    lat: 34.6937,
    lng: 135.5023,
  },
  {
    id: "nagoya",
    place: "Nagoya",
    country: "Japan",
    continent: "Asia",
    lat: 35.1815,
    lng: 136.9066,
  },
  {
    id: "chiang-mai",
    place: "Chiang Mai",
    country: "Thailand",
    continent: "Asia",
    lat: 18.7883,
    lng: 98.9853,
  },
  {
    id: "bangkok",
    place: "Bangkok",
    country: "Thailand",
    continent: "Asia",
    lat: 13.7563,
    lng: 100.5018,
  },
  {
    id: "cebu",
    place: "Cebu",
    country: "Philippines",
    continent: "Asia",
    lat: 10.3157,
    lng: 123.8854,
  },
  {
    id: "vienna",
    place: "Vienna",
    country: "Austria",
    continent: "Europe",
    lat: 48.2082,
    lng: 16.3738,
  },
  {
    id: "munich",
    place: "Munich",
    country: "Germany",
    continent: "Europe",
    lat: 48.1351,
    lng: 11.582,
  },
  {
    id: "dresden",
    place: "Dresden",
    country: "Germany",
    continent: "Europe",
    lat: 51.0504,
    lng: 13.7373,
  },
  {
    id: "prague",
    place: "Prague",
    country: "Czechia",
    continent: "Europe",
    lat: 50.0755,
    lng: 14.4378,
  },
  {
    id: "charlottetown",
    place: "Charlottetown",
    country: "Canada",
    continent: "North America",
    lat: 46.2382,
    lng: -63.1311,
  },
  {
    id: "moncton",
    place: "Moncton",
    country: "Canada",
    continent: "North America",
    lat: 46.0878,
    lng: -64.7782,
  },
  {
    id: "ottawa",
    place: "Ottawa",
    country: "Canada",
    continent: "North America",
    lat: 45.4215,
    lng: -75.6972,
  },
  {
    id: "kingston",
    place: "Kingston",
    country: "Canada",
    continent: "North America",
    lat: 44.2312,
    lng: -76.486,
  },
  {
    id: "venice",
    place: "Venice",
    country: "Italy",
    continent: "Europe",
    lat: 45.4408,
    lng: 12.3155,
  },
  {
    id: "tianjin",
    place: "Tianjin",
    country: "China",
    continent: "Asia",
    lat: 39.0842,
    lng: 117.201,
  },
  {
    id: "suzhou",
    place: "Suzhou",
    country: "China",
    continent: "Asia",
    lat: 31.2989,
    lng: 120.5853,
  },
  {
    id: "wuyuan",
    place: "Wuyuan",
    country: "China",
    continent: "Asia",
    lat: 29.256,
    lng: 117.8485,
  },
  {
    id: "ningde",
    place: "Ningde",
    country: "China",
    continent: "Asia",
    lat: 26.6656,
    lng: 119.5479,
  },
  {
    id: "phnom-penh",
    place: "Phnom Penh",
    country: "Cambodia",
    continent: "Asia",
    lat: 11.5564,
    lng: 104.9282,
  },
  {
    id: "quebec-city",
    place: "Quebec City",
    country: "Canada",
    continent: "North America",
    lat: 46.8139,
    lng: -71.208,
  },
] as const satisfies readonly TravelPlace[];

type TravelPlaceId = (typeof travelPlaces)[number]["id"];

const travelPlacesById = Object.fromEntries(
  travelPlaces.map((place) => [place.id, place]),
) as Record<TravelPlaceId, (typeof travelPlaces)[number]>;

function route(id: string, from: TravelPlaceId, to: TravelPlaceId) {
  return {
    id,
    from: travelPlacesById[from],
    to: travelPlacesById[to],
  };
}

export const travelRoutes = [
  route("fuzhou-toronto", "fuzhou", "toronto"),
  route("toronto-iceland", "toronto", "iceland"),
  route("iceland-toronto", "iceland", "toronto"),
  route("toronto-san-francisco", "toronto", "san-francisco"),
  route("fuzhou-berlin", "fuzhou", "berlin"),
  route("fuzhou-rome", "fuzhou", "rome"),
  route("fuzhou-phuket", "fuzhou", "phuket"),
  route("toronto-halifax", "toronto", "halifax"),
  route("fuzhou-tokyo", "fuzhou", "tokyo"),
  route("fuzhou-manila", "fuzhou", "manila"),
  route("fuzhou-sabah", "fuzhou", "sabah"),
  route("sabah-kuala-lumpur", "sabah", "kuala-lumpur"),
  route("kuala-lumpur-singapore", "kuala-lumpur", "singapore"),
  route("singapore-fuzhou", "singapore", "fuzhou"),
  route("fuzhou-taipei", "fuzhou", "taipei"),
  route("fuzhou-shanghai", "fuzhou", "shanghai"),
  route("fuzhou-beijing", "fuzhou", "beijing"),
  route("fuzhou-xian", "fuzhou", "xian"),
  route("fuzhou-harbin", "fuzhou", "harbin"),
  route("fuzhou-chengdu", "fuzhou", "chengdu"),
  route("fuzhou-zhejiang", "fuzhou", "zhejiang"),
  route("fuzhou-xiamen", "fuzhou", "xiamen"),
  route("fuzhou-shenzhen", "fuzhou", "shenzhen"),
  route("fuzhou-changchun", "fuzhou", "changchun"),
  route("toronto-montreal", "toronto", "montreal"),
  route("montreal-banff", "montreal", "banff"),
  route("san-francisco-la", "san-francisco", "los-angeles"),
  route("san-francisco-hk", "san-francisco", "hong-kong"),
  route("fuzhou-phnom-penh", "fuzhou", "phnom-penh"),
  route("milan-salzburg", "milan", "salzburg"),
  route("vienna-prague", "vienna", "prague"),
  route("prague-amsterdam", "prague", "amsterdam"),
  route("phuket-chiang-mai", "phuket", "chiang-mai"),
  route("chiang-mai-bangkok", "chiang-mai", "bangkok"),
  route("bangkok-fuzhou", "bangkok", "fuzhou"),
  route("montreal-quebec-city", "montreal", "quebec-city"),
  route("halifax-moncton", "halifax", "moncton"),
  route("moncton-charlottetown", "moncton", "charlottetown"),
  route("charlottetown-halifax", "charlottetown", "halifax"),
  route("toronto-kingston", "toronto", "kingston"),
  route("kingston-ottawa", "kingston", "ottawa"),
  route("ottawa-montreal", "ottawa", "montreal"),
] as const;
